#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Rutas para usuario
user:
   path: /usuario
   controller: App\Controller\UserController::index

#Rutas para video
video:
   path: /video
   controller: App\Controller\VideoController::index
